on: [push]

name: Test, Build and Deploy to Google App Engine

jobs:
  test:
    strategy:
      matrix:
        python-version: [ 3.7 ]
        poetry-version: [ 1.1.4 ]
        os: [ ubuntu-18.04 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Poetry Image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Dependencies
        run: |
          cd app
          poetry install --no-root --no-dev

      - name: Run Tests
        run: |
          cd app
          poetry run python -m unittest discover

  deploy:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Construct .env File
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          cd app
          echo "$GCP_SA_KEY" | base64 --decode > key.json
          echo "$ENV_FILE" | base64 --decode > .docker-env

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
